package com.sample

import data.Tuote;
import data.Varasto;
import data.Lasku;
import data.LaskunTila;

ruleflow-group "varastokapasiteetti"
no-loop true

rule "Varastokapasiteetti: Televisio"

    when
       $tuote: Tuote(getNimi().equals("Samsung-televisio"))
       $lasku: Lasku(getTila().equals(LaskunTila.VALMIS))
    then
		Varasto.TELEVISIO = Varasto.TELEVISIO - 1;
end

rule "Varastokapasiteetti: Maito"

    when
       $tuote: Tuote(getNimi().equals("Valio-maito"))
       $lasku: Lasku(getTila().equals(LaskunTila.VALMIS))
    then
		Varasto.MAITO = Varasto.MAITO - 1;
end

rule "Varastokapasiteetti: Kirja"

    when
       $tuote: Tuote(getNimi().equals("Kalevala"))
       $lasku: Lasku(getTila().equals(LaskunTila.VALMIS))
    then
		Varasto.KIRJA = Varasto.KIRJA - 1;
end

rule "Varastokapasiteetti: Jakkara"

    when
       $tuote: Tuote(getNimi().equals("Artek-jakkara"))
       $lasku: Lasku(getTila().equals(LaskunTila.VALMIS))
    then
		Varasto.JAKKARA = Varasto.JAKKARA - 1;
end
