package com.sample
 
import data.Tuote;
import data.Tuotetyypit;
 
rule "24"
    when
        tuote : Tuote( tyyppi == Tuotetyypit.LUOKKA1)
    then
        tuote.setHinta(tuote.getHinta() + (tuote.getHinta() * 0.24));
        System.out.println("Tuotteen '" + tuote.getNimi() + "' hinta (sis. alv) on " + tuote.getHinta());
end

rule "14"
    when 
        tuote : Tuote( tyyppi == Tuotetyypit.LUOKKA2)
    then
    	tuote.setHinta(tuote.getHinta() + (tuote.getHinta() * 0.14));
        System.out.println("Tuotteen '" + tuote.getNimi() + "' hinta (sis. alv) on " + tuote.getHinta());
       
end

rule "10"
    when
        tuote : Tuote( tyyppi == Tuotetyypit.LUOKKA3)
    then
        tuote.setHinta(tuote.getHinta() + (tuote.getHinta() * 0.1));
        System.out.println("Tuotteen '" + tuote.getNimi() + "' hinta (sis. alv) on " + tuote.getHinta());
end

rule "0"
    when
        tuote : Tuote( tyyppi == Tuotetyypit.LUOKKA4)
    then
        tuote.setHinta(tuote.getHinta() + (tuote.getHinta() * 0));
        System.out.println("Tuotteen '" + tuote.getNimi() + "' hinta (sis. alv) on " + tuote.getHinta());
end
