package com.sample
 
import data.Tuote;
import data.Tuotetyypit;

rule "Luokka 1: ALV-prosentti 24"
    when
        tuote : Tuote( tyyppi == Tuotetyypit.LUOKKA1)
    then
        tuote.setHinta(tuote.getHinta() + (tuote.getHinta() * Tuotetyypit.LUOKKA1_KERROIN));
end

rule "Luokka 2: ALV-prosentti 14"
    when 
        tuote : Tuote( tyyppi == Tuotetyypit.LUOKKA2)
    then
    	tuote.setHinta(tuote.getHinta() + (tuote.getHinta() * Tuotetyypit.LUOKKA2_KERROIN)); 
end

rule "Luokka 3: ALV-prosentti 10"
    when
        tuote : Tuote( tyyppi == Tuotetyypit.LUOKKA3)
    then
        tuote.setHinta(tuote.getHinta() + (tuote.getHinta() * Tuotetyypit.LUOKKA3_KERROIN));
end

rule "Luokka 4: ALV-prosentti 0"
    when
        tuote : Tuote( tyyppi == Tuotetyypit.LUOKKA4)
    then
        tuote.setHinta(tuote.getHinta() + (tuote.getHinta() * Tuotetyypit.LUOKKA4_KERROIN));
end
